### PR TITLE
feat: add M5StackChan servo driver scaffold

### LINKED ISSUE #407: Step 1: M5StackChan CoreS3 シリアルサーボ移植
## 概要
M5Stack/StackChan CoreS3 の Feetech/SCServo 系シリアルサーボを `stack-chan/stack-chan` に移植する第一歩です。

## 仕様メモ
参照元: `M5Stack/StackChan firmware/main/hal/hal_servo.cpp`

- UART: TX GPIO 6 / RX GPIO 7 / baud 1,000,000
- yaw: id 1, defaultZeroPos 460, angleLimit -1280..1280, rawPosLimit 0..1000
- pitch: id 2, defaultZeroPos 620, angleLimit 0..900, rawPosLimit 0..1000
- raw 変換: `zeroPos + angle * 16 / 5 / 10`
- pitch は 0..900 の範囲に制限
- servo 内部 offset register をいきなり書き換えず、まず app/config 側の zeroPos で raw 目標値を計算する

## 実装案
- 既存 `scservo.ts` の通信層を再利用できるよう raw-position helper を追加、または M5StackChan 専用 driver を追加
- `m5stackchan` driver type と config を追加
- 最初の PR では純粋な変換・制限・config を TDD で固める

## 受け入れ条件
- yaw/pitch の angle -> raw position 変換がテストされている
- raw position が 0..1000 に clamp される
- CoreS3 用 config が TX=6/RX=7 と M5StackChan 原点を表現できる
- PR body に実機での安全確認手順が書かれている

---
Part of #406

### PR DESCRIPTION
**Pull request by meganetaaan**
## Summary
- Adds a M5StackChan-specific SCServo mapping layer using the source firmware CoreS3 calibration values.
- Adds a `m5stackchan` driver scaffold that sends raw SCServo positions instead of rewriting servo offset registers.
- Adds `manifest_m5stackchan_cores3.json` with TX=6/RX=7/1Mbps and yaw/pitch zero positions 460/620.
- Repairs the unit-test TypeScript emit path so `npm run test:unit` actually runs emitted Node test files.

Closes #407
Part of #406

## Source firmware references
- `M5Stack/StackChan@51a0617 firmware/main/hal/hal_servo.cpp`
- yaw: id=1, defaultZeroPos=460, angleLimit=-1280..1280, rawPosLimit=0..1000
- pitch: id=2, defaultZeroPos=620, angleLimit=0..900, rawPosLimit=0..1000
- serial: TX GPIO 6, RX GPIO 7, baud 1,000,000

## Test Plan
- [x] RED observed: `npm run test:unit` failed on missing `m5stackchan-servo.js` after adding tests.
- [x] `npm run test:unit`
- [x] `npm run format`
- [x] `npm run lint` — exits 0; existing warning remains in `stackchan/renderers-piu/drawer.ts:198`.
- [x] `mcconfig -d -m -p esp32/m5stack_cores3 -t build ./stackchan/manifest_m5stackchan_cores3.json`

## Device safety notes
- This PR does not write SCServo offset registers.
- Raw position commands are clamped to 0..1000 through the M5StackChan mapping layer before dispatch.
- First real-device validation should start with torque off/on, present-position reads, then very small yaw/pitch movements around zero.

## Summary by CodeRabbit

* **New Features**
  * Support for M5StackChan CoreS3 platform with power setup and device wiring
  * New M5StackChan servo backend (yaw/pitch) and PY32 LED driver with shared I/O expander and color/effect controls

* **Improvements**
  * Safer servo angle/position conversions and more flexible servo communication/options
  * LED initialization validates configs and skips invalid entries with logs

* **Tests**
  * Unit tests for servo mapping and PY32 expander/LED helpers

* **Chores**
  * Updated unit test runner invocation and test TypeScript config

[Review Change Stack](https://app.coderabbit.ai/change-stack/stack-chan/stack-chan/pull/413)

### CODE REVIEW

**Comment by meganetaaan** [comment]
## CI note

The PR-specific CoreS3/custom-manifest build passes locally, but two GitHub Actions checks are currently red with the same `undefined reference to app_main` linker failure seen on the current `dev/v1.0` base branch runs.

Evidence:
- Current base `dev/v1.0` Build Stack-chan Firmware is already red: https://github.com/stack-chan/stack-chan/actions/runs/24948326219
- Current base `dev/v1.0` Bundle Stack-chan Firmware is already red: https://github.com/stack-chan/stack-chan/actions/runs/24948326221
- PR rerun failures show linker error in the default `esp32/m5stack` build:
  - `undefined reference to app_main`

Local verification in this worktree:
- `npm run test:unit` PASS
- `npm run format` PASS
- `npm run lint` exits 0 with existing warning in `stackchan/renderers-piu/drawer.ts:198`
- `npm run build` PASS for default `esp32/m5stack`
- `mcconfig -d -m -p esp32/m5stack_cores3 -t build ./stackchan/manifest_m5stackchan_cores3.json` PASS

So I am treating the failing GitHub checks as an existing base/CI environment issue rather than a regression introduced by #413.

**Comment by meganetaaan** [comment]
@coderabbitai レビューしてください
