### ISSUE TITLE
Stack-chan fails to build on Moddable v4.2.0

### ISSUE THREAD

**Issue by meganetaaan** [meganetaaan/stack-chan#215]
**Describe the bug**
Stack-chan fails to build on Moddable v4.2.0

**To Reproduce**
1. Update Moddable SDK to v4.2.0
2. Update ESP-IDF to v5.1.1
3. run `npm run debug`

**Logs**
If any compile error occurs, add a full compile log.

`pins/servo` module seems to be incompatible with the latest ESP-IDF (v5.1.1)

````log
# cc modServo.c.o
# cc crc.c.o
/home/sskw/.local/share/moddable/modules/pins/servo/esp32/modServo.c: In function 'xs_servo':
/home/sskw/.local/share/moddable/modules/pins/servo/esp32/modServo.c:58:18: error: 'ledc_timer_config_t' has no member named 'bit_num'
   58 |                 .bit_num = LEDC_TIMER_14_BIT,
      |                  ^~~~~~~
make: *** [/home/sskw/.local/share/moddable/build/tmp/esp32/m5stack/debug/stackchan/makefile:2591: /home/sskw/.local/share/moddable/build/tmp/esp32/m5stack/debug/stackchan/modServo.c.o] エラー 1
make: *** 未完了のジョブを待っています....
# cc modules.c.o
````

<details>
<summary>complete log</summary>

```
[sskw]$ npm run debug target=esp32/m5stack_core2            

> stack-chan@0.2.1 debug /work/ghq/github.com/meganetaaan/stack-chan/firmware
> cross-env npm_config_target?=esp32/m5stack cross-env-shell mcconfig -d -m -p \$npm_config_target ./stackchan/manifest_local.json "target=esp32/m5stack_core2"

mcconfig: mod partition of size 0x40000 created from factory app partition
mcconfig: file storage partition of size 0x10000 created from factory app partition
/home/sskw/.local/share/esp32/esp-idf-v5.1.1/tools/idf.py
/home/sskw/.local/share/moddable/build/tmp/esp32/m5stack/debug/stackchan/makefile:2376: 警告: ターゲット '/home/sskw/.local/share/moddable/build/tmp/esp32/m5stack/debug/stackchan/ftimage.h.xsi' のためのレシピを置き換えます
/home/sskw/.local/share/moddable/build/tmp/esp32/m5stack/debug/stackchan/makefile:2307: 警告: ターゲット '/home/sskw/.local/share/moddable/build/tmp/esp32/m5stack/debug/stackchan/ftimage.h.xsi' のための古いレシピは無視されます
# bles2gatt bleservices
Using recommended ESP-IDF v5.1.1
# xsc Resource.xsb
# xsc ili9341.xsb
# xsc m5button.xsb
# xsc time.xsb
# xsc timer.xsb
# xsc modules.xsb
# xsc crc.xsb
# xsc net.xsb
# xsc socket.xsb
# xsc sntp.xsb
# xsc wifi.xsb
# xsc preference.xsb
# xsc structuredClone.xsb
# xsc deepEqual.xsb
# xsc bleserver.xsb
# xsc btutils.xsb
# xsc gap.xsb
# xsc gapwhitelist.xsb
# xsc sm.xsb
# xsc bleclient.xsb
# xsc connection.xsb
# xsc gatt.xsb
# xsc uartserver.xsb
# xsc stk-server.xsb
# xsc crypt.xsb
# xsc base64.xsb
# xsc hex.xsb
# xsc ec.xsb
# xsc ecp.xsb
# xsc modular.xsb
# xsc mont.xsb
# xsc tlssocket.xsb
# xsc fetch.xsb
# xsc config.xsb
# xsc logical.xsb
# xsc WebSocket.xsb
# xsc mdns.xsb
# xsc dns.xsb
# xsc resourcestreamer.xsb
# xsc mp3streamer.xsb
# xsc elevenlabsstreamer.xsb
# xsc wavstreamer.xsb
# xsc sbcstreamer.xsb
# xsc calculate-power.xsb
# xsc pins/digital.xsb
# xsc commodetto/Bitmap.xsb
# xsc pins/digital/monitor.xsb
# xsc pins/audioout.xsb
# xsc setup/target.xsb
# xsc m5stack/screen.xsb
# xsc pins/servo.xsb
# xsc setup/network.xsb
# xsc ~.embedded/io/analog.xsb
# xsc ~.embedded/io/digital.xsb
# xsc ~.embedded/io/digitalbank.xsb
# xsc ~.embedded/io/i2c.xsb
# xsc ~.embedded/implementation/i2csync.xsb
# xsc ~.embedded/io/smbus.xsb
# xsc ~.embedded/implementation/smbussync.xsb
# xsc ~.embedded/io/pwm.xsb
# xsc ~.embedded/io/serial.xsb
# xsc ~.embedded/io/spi.xsb
# xsc ~.embedded/io/socket/tcp.xsb
# xsc ~.embedded/io/socket/udp.xsb
# xsc ~.embedded/io/socket/listener.xsb
# xsc system.xsb
# xsc ~.embedded/provider/builtin.xsb
# xsc ~.embedded/io/pulsecount.xsb
# xsc ~.embedded/io/pulsewidth.xsb
# xsc headers.xsb
# xsc url.xsb
# xsc ~.embedded/network/dns/resolver/udp.xsb
# xsc dns/parser.xsb
# xsc dns/serializer.xsb
# xsc httpclient/config.xsb
# xsc ~.embedded/network/http/client.xsb
# xsc bin.xsb
# xsc ssl/alert.xsb
# xsc ssl/cache.xsb
# xsc ssl/cert.xsb
# xsc ssl/changecipher.xsb
# xsc ssl/ciphersuites.xsb
# xsc ssl/constants.xsb
# xsc ssl/error.xsb
# xsc ssl/handshake.xsb
# xsc ssl/prf.xsb
# xsc ssl/record.xsb
# xsc ssl/setup.xsb
# xsc ssl/stream.xsb
# xsc ber.xsb
# xsc curve.xsb
# xsc dsa.xsb
# xsc ecdsa.xsb
# xsc gcm.xsb
# xsc hmac.xsb
# xsc pkcs1_5.xsb
# xsc pkcs1.xsb
# xsc pkcs8.xsb
# xsc rng.xsb
# xsc rsa.xsb
# xsc x509.xsb
# xsc ssl/session.xsb
# xsc httpsclient/config.xsb
# xsc commodetto/parseBMF.xsb
# xsc commodetto/parseBMP.xsb
# xsc commodetto/parseRLE.xsb
# xsc commodetto/Poco.xsb
# xsc commodetto/PocoCore.xsb
# xsc setup/commodetto.xsb
# xsc commodetto/outline.xsb
# xsc commodetto/pocoOutline.xsb
# xsc text/decoder.xsb
# xsc ~.embedded/network/websocket/client.xsb
# xsc mp3/decode.xsb
# xsc file.xsb
# xsc data/wavreader.xsb
# xsc mc/config.xsb
# tsc tsconfig.json
# xsid Resource.c.xsi
# xsid modGPIO.c.xsi
# xsid modSPI.c.xsi
# xsid modIli9341.c.xsi
# xsid modMonitor.c.xsi
# xsid modTime.c.xsi
# xsid modTimer.c.xsi
# xsid timer.c.xsi
# xsid modPreference.c.xsi
# xsid modInstrumentation.c.xsi
# xsid modLwipSafe.c.xsi
# xsid modules.c.xsi
# xsid crc.c.xsi
# xsid modServo.c.xsi
# xsid modNet.c.xsi
# xsid modResolve.c.xsi
# xsid modSocket.c.xsi
# xsid modsntp.c.xsi
# xsid xs6wifi.c.xsi
# xsid builtinCommon.c.xsi
# xsid digitalbank.c.xsi
# xsid _i2c.c.xsi
# xsid spi.c.xsi
# xsid structuredClone.c.xsi
# xsid deepEqual.c.xsi
# xsid btutils.c.xsi
# xsid gap.c.xsi
# xsid modBLEServer.c.xsi
# xsid modBLESM.c.xsi
# xsid modBLEGAP.c.xsi
# xsid modBLECommon.c.xsi
# xsid modBLEClient.c.xsi
# xsid moddnsparser.c.xsi
# xsid modCrypt.c.xsi
# xsid chacha.c.xsi
# xsid fips180.c.xsi
# xsid fips197.c.xsi
# xsid fips46.c.xsi
# xsid ghash.c.xsi
# xsid rc.c.xsi
# xsid rfc1321.c.xsi
# xsid modBase64.c.xsi
# xsid modHex.c.xsi
# xsid ec.c.xsi
# xsid modular.c.xsi
# xsid mont.c.xsi
# xsid xsBigIntEx.c.xsi
# xsid ftcalc.c.xsi
# xsid ftgrays.c.xsi
# xsid ftraster.c.xsi
# xsid ftstroke.c.xsi
# xsid fttrigon.c.xsi
# xsid ftutil.c.xsi
# xsid modLogical.c.xsi
# xsid bit.c.xsi
# xsid fixed.c.xsi
# xsid frame.c.xsi
# xsid huffman.c.xsi
# xsid layer3.c.xsi
# xsid stream.c.xsi
# xsid synth.c.xsi
# xsid mad_timer.c.xsi
# xsid lfs.c.xsi
# xsid lfs_util.c.xsi
# xsid modLittlefs.c.xsi
# xsid wavstreamer.c.xsi
# xsid calculatePower.c.xsi
# xsid digital.c.xsi
# xsid commodettoBitmap.c.xsi
# xsid audioout.c.xsi
# xsid dvi_adpcm_decode.c.xsi
# xsid sbc_decoder.c.xsi
# xsid commodettoPocoBlit.c.xsi
# xsid _analog.c.xsi
# xsid _pwm.c.xsi
# xsid serial.c.xsi
# xsid tcp.c.xsi
# xsid udp.c.xsi
# xsid system.c.xsi
# xsid _pulsecount.c.xsi
# xsid _pulsewidth.c.xsi
# xsid url.c.xsi
# xsid bin.c.xsi
# xsid rng.c.xsi
# xsid x509.c.xsi
# xsid commodettoParseBMF.c.xsi
# xsid commodettoParseBMP.c.xsi
# xsid commodettoParseRLE.c.xsi
# xsid commodettoPocoCore.c.xsi
# xsid cfeBMF.c.xsi
# xsid commodettoOutline.c.xsi
# xsid commodettoPocoOutline.c.xsi
# xsid textdecoder.c.xsi
# xsid mp3.c.xsi
# xsid modGPIO.h.xsi
# xsid modSPI.h.xsi
# xsid modTimer.h.xsi
# xsid modPreference.h.xsi
# xsid modInstrumentation.h.xsi
# xsid modLwipSafe.h.xsi
# xsid modSocket.h.xsi
# xsid builtinCommon.h.xsi
# xsid modBLE.h.xsi
# xsid modBLECommon.h.xsi
# xsid chacha.h.xsi
# xsid fips180.h.xsi
# xsid fips197.h.xsi
# xsid fips46.h.xsi
# xsid ghash.h.xsi
# xsid kcl.h.xsi
# xsid kcl_symmetric.h.xsi
# xsid rc.h.xsi
# xsid rfc1321.h.xsi
# xsid xsBigIntEx.h.xsi
# xsid ftgrays.h.xsi
# xsid ftimage.h.xsi
# xsid ftmisc.h.xsi
# xsid ftraster.h.xsi
# xsid rasterrs.h.xsi
# xsid ft2build.h.xsi
# xsid freetype.h.xsi
# xsid ftadvanc.h.xsi
# xsid ftbbox.h.xsi
# xsid ftbdf.h.xsi
# xsid ftbitmap.h.xsi
# xsid ftbzip2.h.xsi
# xsid ftcache.h.xsi
# xsid ftchapters.h.xsi
# xsid ftcid.h.xsi
# xsid ftcolor.h.xsi
# xsid ftdriver.h.xsi
# xsid fterrdef.h.xsi
# xsid fterrors.h.xsi
# xsid ftfntfmt.h.xsi
# xsid ftgasp.h.xsi
# xsid ftglyph.h.xsi
# xsid ftgxval.h.xsi
# xsid ftgzip.h.xsi
# xsid ftincrem.h.xsi
# xsid ftlcdfil.h.xsi
# xsid ftlist.h.xsi
# xsid ftlogging.h.xsi
# xsid ftlzw.h.xsi
# xsid ftmac.h.xsi
# xsid ftmm.h.xsi
# xsid ftmodapi.h.xsi
# xsid ftmoderr.h.xsi
# xsid ftotval.h.xsi
# xsid ftoutln.h.xsi
# xsid ftparams.h.xsi
# xsid ftpfr.h.xsi
# xsid ftrender.h.xsi
# xsid ftsizes.h.xsi
# xsid ftsnames.h.xsi
# xsid ftstroke.h.xsi
# xsid ftsynth.h.xsi
# xsid ftsystem.h.xsi
# xsid fttrigon.h.xsi
# xsid fttypes.h.xsi
# xsid ftwinfnt.h.xsi
# xsid t1tables.h.xsi
# xsid ttnameid.h.xsi
# xsid tttables.h.xsi
# xsid tttags.h.xsi
# xsid autohint.h.xsi
# xsid cffotypes.h.xsi
# xsid cfftypes.h.xsi
# xsid compiler-macros.h.xsi
# xsid ftcalc.h.xsi
# xsid ftdebug.h.xsi
# xsid ftdrv.h.xsi
# xsid ftgloadr.h.xsi
# xsid fthash.h.xsi
# xsid ftmemory.h.xsi
# xsid ftobjs.h.xsi
# xsid ftpsprop.h.xsi
# xsid ftrfork.h.xsi
# xsid ftserv.h.xsi
# xsid ftstream.h.xsi
# xsid fttrace.h.xsi
# xsid ftvalid.h.xsi
# xsid bit.h.xsi
# xsid fixed.h.xsi
# xsid frame.h.xsi
# xsid huffman.h.xsi
# xsid layer3.h.xsi
# xsid stream.h.xsi
# xsid synth.h.xsi
# xsid lfs.h.xsi
# xsid lfs_util.h.xsi
# xsid commodettoBitmap.h.xsi
# xsid sbc_decoder.h.xsi
# xsid commodettoPocoBlit.h.xsi
# xsid commodettoPoco.h.xsi
# xsid commodettoPocoOutline.h.xsi
# copy ca233.der
# copy ca.ski
# png2bmp OpenSans-Regular-24-alpha.bmp
# wav2maud bflatmajor.maud
# Reconfiguring ESP-IDF...
# compressbmf OpenSans-Regular-24.bf4
Executing action: reconfigure
Running cmake in directory /home/sskw/.local/share/moddable/build/tmp/esp32/m5stack/debug/stackchan/xsProj-esp32/build
Executing "cmake -G Ninja -DPYTHON_DEPS_CHECKED=1 -DPYTHON=/home/sskw/.espressif/python_env/idf5.1_py3.10_env/bin/python -DESP_PLATFORM=1 -DSDKCONFIG_DEFAULTS=/home/sskw/.local/share/moddable/build/tmp/esp32/m5stack/debug/stackchan/xsProj-esp32/sdkconfig.mc -DSDKCONFIG_HEADER=/home/sskw/.local/share/moddable/build/tmp/esp32/m5stack/debug/stackchan/xsProj-esp32/build/config/sdkconfig.h -DCMAKE_MESSAGE_LOG_LEVEL=ERROR -DDEBUGGER_SPEED=460800 -DIDF_TARGET=esp32 -DESP32_SUBCLASS=esp32 -DCCACHE_ENABLE=0 /home/sskw/.local/share/moddable/build/tmp/esp32/m5stack/debug/stackchan/xsProj-esp32"...
# xsc scservo.xsb
# xsc rs30x.xsb
# xsc consts.xsb
# xsc stackchan-util.xsb
# xsc dynamixel-driver.xsb
# xsc dynamixel.xsb
# xsc none-driver.xsb
# xsc rs30x-driver.xsb
# xsc scservo-driver.xsb
# xsc sg90-driver.xsb
# xsc beacon-packet.xsb
# xsc dialogue-chatgpt.xsb
# xsc decorator.xsb
# xsc dog-face.xsb
# xsc modifier.xsb
# xsc renderer-base.xsb
# xsc simple-face.xsb
# xsc network-service.xsb
# xsc preference-server.xsb
# xsc tts-elevenlabs.xsb
# xsc tts-local.xsb
# xsc tts-remote.xsb
# xsc tts-voicevox.xsb
# xsc touch.xsb
# xsc robot.xsb
# xsc main.xsb
# xsc default-mods/mod.xsb
# xsc default-mods/on-launch.xsb
# xsc default-mods/on-robot-created.xsb
Loading defaults file /home/sskw/.local/share/moddable/build/tmp/esp32/m5stack/debug/stackchan/xsProj-esp32/sdkconfig.mc...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/sskw/.local/share/moddable/build/tmp/esp32/m5stack/debug/stackchan/xsProj-esp32/build
# cc xsAll.c (strings in flash)
# cc xsAPI.c (strings in flash)
# cc xsArguments.c (strings in flash)
# cc xsArray.c (strings in flash)
# cc xsAtomics.c (strings in flash)
# cc xsBigInt.c (strings in flash)
# cc xsBoolean.c (strings in flash)
# cc xsCode.c (strings in flash)
# cc xsCommon.c (strings in flash)
# cc xsDataView.c (strings in flash)
# cc xsDate.c (strings in flash)
/home/sskw/.local/share/moddable/xs/sources/xsBigInt.c: In function 'fxBigInt_uadd_prim':
/home/sskw/.local/share/moddable/xs/sources/xsBigInt.c:1363:51: warning: passing argument 3 of '__builtin_uadd_overflow' from incompatible pointer type [-Wincompatible-pointer-types]
 1363 |         if (__builtin_uadd_overflow(ap[i], bp[i], &r)) {
      |                                                   ^~
      |                                                   |
      |                                                   txU4 * {aka long unsigned int *}
/home/sskw/.local/share/moddable/xs/sources/xsBigInt.c:1363:51: note: expected 'unsigned int *' but argument is of type 'txU4 *' {aka 'long unsigned int *'}
/home/sskw/.local/share/moddable/xs/sources/xsBigInt.c:1368:51: warning: passing argument 3 of '__builtin_uadd_overflow' from incompatible pointer type [-Wincompatible-pointer-types]
 1368 |                 c = __builtin_uadd_overflow(r, c, &rp[i]);
      |                                                   ^~~~~~
      |                                                   |
      |                                                   txU4 * {aka long unsigned int *}
/home/sskw/.local/share/moddable/xs/sources/xsBigInt.c:1368:51: note: expected 'unsigned int *' but argument is of type 'txU4 *' {aka 'long unsigned int *'}
/home/sskw/.local/share/moddable/xs/sources/xsBigInt.c:1374:55: warning: passing argument 3 of '__builtin_uadd_overflow' from incompatible pointer type [-Wincompatible-pointer-types]
 1374 |                 c = __builtin_uadd_overflow(1, bp[i], &rp[i]);
      |                                                       ^~~~~~
      |                                                       |
      |                                                       txU4 * {aka long unsigned int *}
/home/sskw/.local/share/moddable/xs/sources/xsBigInt.c:1374:55: note: expected 'unsigned int *' but argument is of type 'txU4 *' {aka 'long unsigned int *'}
# mcrez resources
# xsl modules
# cc xsHosts.c (strings in flash)
# cc xsHost.c (strings in flash)
# cc xsPlatform.c (strings in flash)
# cc e_pow.c (strings in flash)
# cc xsmc.c (strings in flash)
# cc xsre.c (strings in flash)
# cc xsdtoa.c (strings in flash)
# cc xsType.c (strings in flash)
Total resource size: 44621 bytes
# cc xsTree.c (strings in flash)
# cc xsSyntaxical.c (strings in flash)
# cc xsSymbol.c (strings in flash)
# cc mc.resources.c (slots in flash)
# cc xsString.c (strings in flash)
/tmp/ccc4kILn.s: Assembler messages:
/tmp/ccc4kILn.s:2934: Warning: setting incorrect section attributes for .rodata.mod.0
# cc xsSourceMap.c (strings in flash)
# cc xsScript.c (strings in flash)
# cc xsScope.c (strings in flash)
# cc xsRun.c (strings in flash)
# cc xsRegExp.c (strings in flash)
# cc xsProxy.c (strings in flash)
# cc xsProperty.c (strings in flash)
# cc xsPromise.c (strings in flash)
# cc xsObject.c (strings in flash)
# cc xsNumber.c (strings in flash)
# cc xsModule.c (strings in flash)
# cc xsMemory.c (strings in flash)
# cc xsMath.c (strings in flash)
# cc xsMarshall.c (strings in flash)
# cc xsMapSet.c (strings in flash)
# cc xsLexical.c (strings in flash)
# cc xsJSON.c (strings in flash)
# cc xsGlobal.c (strings in flash)
# cc xsGenerator.c (strings in flash)
# cc xsFunction.c (strings in flash)
# cc xsError.c (strings in flash)
# cc xsDebug.c (strings in flash)
### 3004 instances, 2749 keys, 138 colors, 0 holes
### warning: consts: DOMAIN: not frozen
### warning: dynamixel: BAUDRATE: not frozen
### warning: dynamixel: OPERATING_MODE: not frozen
### warning: dynamixel: default() 0() 0() INSTRUCTION: not frozen
### warning: dynamixel: default() 0() 0() packetHandler: no const
### warning: dynamixel: default() PacketHandler() RX_STATE: not frozen
### warning: dynamixel: default.prototype.setOperatingMode() ADDRESS: not frozen
### warning: rs30x-driver: RS30XDriver() RS30X() 0() 0() packetHandler: no const
### warning: rs30x-driver: RS30XDriver() RS30X() PacketHandler() RX_STATE: not frozen
### warning: rs30x-driver: RS30XDriver() RS30X() PacketHandler() PACKET_TYPE: not frozen
### warning: rs30x-driver: RS30XDriver() RS30X.prototype.setMaxTorque() COMMANDS.SET_MAX_ANGLE: not frozen
### warning: scservo-driver: SCServoDriver() SCServo() 0() 0() packetHandler: no const
### warning: scservo-driver: SCServoDriver() SCServo() 0() 0() COMMAND: not frozen
### warning: scservo-driver: SCServoDriver() SCServo() 0() 0() ADDRESS: not frozen
### warning: scservo-driver: SCServoDriver() SCServo() PacketHandler() RX_STATE: not frozen
### warning: ssl/cache: default: not frozen
### warning: ssl/cert: default.prototype.getKey() globalCerts: not frozen
### warning: fetch: fetch() fetchClientRequest() clients: no const
### warning: renderer-base: defaultFaceContext: not frozen
### warning: renderer-base: defaultFaceContext.mouth: not frozen
### warning: renderer-base: defaultFaceContext.eyes: not frozen
### warning: renderer-base: defaultFaceContext.eyes.left: not frozen
### warning: renderer-base: defaultFaceContext.eyes.right: not frozen
### warning: renderer-base: defaultFaceContext.theme: not frozen
### warning: renderer-base: defaultFaceContext.theme.primary: not frozen
### warning: renderer-base: defaultFaceContext.theme.secondary: not frozen
### warning: WebSocket: default() URLParts() urlRegExp: no const
### warning: WebSocket: default() URLParts() authorityRegExp: no const
### warning: tts-remote: TTS.prototype.stream() streamer: no const
# cc mc.xs.c (slots in flash)
# cc Resource.c.o
# cc modGPIO.c.o
# cc modSPI.c.o
# cc modIli9341.c.o
# cc modMonitor.c.o
# cc modTime.c.o
# cc modTimer.c.o
# cc timer.c.o
# cc modPreference.c.o
# cc mp3.c.o
# cc textdecoder.c.o
# cc commodettoPocoOutline.c.o
# cc commodettoOutline.c.o
# cc cfeBMF.c.o
# cc commodettoPocoCore.c.o
# cc commodettoParseRLE.c.o
# cc commodettoParseBMP.c.o
# cc commodettoParseBMF.c.o
# cc x509.c.o
# cc rng.c.o
# cc bin.c.o
# cc url.c.o
# cc _pulsewidth.c.o
# cc _pulsecount.c.o
# cc system.c.o
# cc udp.c.o
# cc tcp.c.o
# cc serial.c.o
# cc _pwm.c.o
# cc _analog.c.o
# cc commodettoPocoBlit.c.o
# cc sbc_decoder.c.o
# cc dvi_adpcm_decode.c.o
# cc audioout.c.o
# cc commodettoBitmap.c.o
# cc digital.c.o
# cc calculatePower.c.o
# cc wavstreamer.c.o
# cc modLittlefs.c.o
# cc lfs_util.c.o
# cc lfs.c.o
# cc mad_timer.c.o
# cc synth.c.o
# cc stream.c.o
# cc layer3.c.o
# cc huffman.c.o
# cc frame.c.o
# cc fixed.c.o
# cc bit.c.o
# cc modLogical.c.o
# cc ftutil.c.o
# cc fttrigon.c.o
# cc ftstroke.c.o
# cc ftraster.c.o
# cc ftgrays.c.o
# cc ftcalc.c.o
# cc xsBigIntEx.c.o
# cc mont.c.o
In function 'sdctII',
    inlined from 'dctIV' at /home/sskw/.local/share/moddable/modules/data/mp3/libmad/layer3.c:1782:3,
    inlined from 'imdct36' at /home/sskw/.local/share/moddable/modules/data/mp3/libmad/layer3.c:1809:3,
    inlined from 'III_imdct_l' at /home/sskw/.local/share/moddable/modules/data/mp3/libmad/layer3.c:2135:3:
/home/sskw/.local/share/moddable/modules/data/mp3/libmad/layer3.c:1742:3: warning: 'fastsdct' accessing 72 bytes in a region of size 68 [-Wstringop-overflow=]
 1742 |   fastsdct(tmp, &X[1]);
      |   ^~~~~~~~~~~~~~~~~~~~
/home/sskw/.local/share/moddable/modules/data/mp3/libmad/layer3.c:1742:3: note: referencing argument 2 of type 'mad_fixed_t[18]' {aka 'int[18]'}
/home/sskw/.local/share/moddable/modules/data/mp3/libmad/layer3.c: In function 'III_imdct_l':
/home/sskw/.local/share/moddable/modules/data/mp3/libmad/layer3.c:1640:6: note: in a call to function 'fastsdct'
 1640 | void fastsdct(mad_fixed_t const x[9], mad_fixed_t y[18])
      |      ^~~~~~~~
# cc modular.c.o
# cc ec.c.o
# cc modHex.c.o
In function 'sdctII',
    inlined from 'dctIV' at /home/sskw/.local/share/moddable/modules/data/mp3/libmad/layer3.c:1782:3,
    inlined from 'imdct36' at /home/sskw/.local/share/moddable/modules/data/mp3/libmad/layer3.c:1809:3,
    inlined from 'III_imdct_l' at /home/sskw/.local/share/moddable/modules/data/mp3/libmad/layer3.c:2135:3:
/home/sskw/.local/share/moddable/modules/data/mp3/libmad/layer3.c:1742:3: warning: 'fastsdct' accessing 72 bytes in a region of size 68 [-Wstringop-overflow=]
 1742 |   fastsdct(tmp, &X[1]);
      |   ^~~~~~~~~~~~~~~~~~~~
/home/sskw/.local/share/moddable/modules/data/mp3/libmad/layer3.c:1742:3: note: referencing argument 2 of type 'mad_fixed_t[18]' {aka 'int[18]'}
/home/sskw/.local/share/moddable/modules/data/mp3/libmad/layer3.c: In function 'III_imdct_l':
/home/sskw/.local/share/moddable/modules/data/mp3/libmad/layer3.c:1640:6: note: in a call to function 'fastsdct'
 1640 | void fastsdct(mad_fixed_t const x[9], mad_fixed_t y[18])
      |      ^~~~~~~~
# cc modBase64.c.o
# cc rfc1321.c.o
# cc rc.c.o
# cc ghash.c.o
# cc fips46.c.o
# cc fips197.c.o
# cc fips180.c.o
# cc chacha.c.o
# cc modCrypt.c.o
# cc moddnsparser.c.o
/tmp/cc0B2IF5.s: Assembler messages:
/tmp/cc0B2IF5.s:763: Warning: setting incorrect section attributes for .rodata.mod.0
# cc modBLEClient.c.o
# cc modBLECommon.c.o
# cc modBLEGAP.c.o
# cc modBLESM.c.o
# cc modBLEServer.c.o
# cc gap.c.o
# cc btutils.c.o
# cc deepEqual.c.o
# cc structuredClone.c.o
# cc spi.c.o
# cc _i2c.c.o
# cc digitalbank.c.o
# cc builtinCommon.c.o
# cc xs6wifi.c.o
# cc modsntp.c.o
# cc modSocket.c.o
# cc modResolve.c.o
# cc modNet.c.o
# cc modServo.c.o
# cc crc.c.o
/home/sskw/.local/share/moddable/modules/pins/servo/esp32/modServo.c: In function 'xs_servo':
/home/sskw/.local/share/moddable/modules/pins/servo/esp32/modServo.c:58:18: error: 'ledc_timer_config_t' has no member named 'bit_num'
   58 |                 .bit_num = LEDC_TIMER_14_BIT,
      |                  ^~~~~~~
make: *** [/home/sskw/.local/share/moddable/build/tmp/esp32/m5stack/debug/stackchan/makefile:2591: /home/sskw/.local/share/moddable/build/tmp/esp32/m5stack/debug/stackchan/modServo.c.o] エラー 1
make: *** 未完了のジョブを待っています....
# cc modules.c.o
```
</details>

- OS: Linux
- Stack Chan Version: latest `dev/v1.0` branch
- Type of M5Stack to use: M5Stack Core2

**Comment by stc1988** [comment]
https://github.com/Moddable-OpenSource/moddable/issues/1088

I can't confirm it right now, but hasn't this problem been solved yet?

**Comment by meganetaaan** [comment]
I've found that another commit rolled back your fix. I made a PR to get them back.
https://github.com/Moddable-OpenSource/moddable/pull/1225

**Comment by meganetaaan** [comment]
I've found several issues that block firmware build.
As a workaround, I'm going to fix the version of ModdableSDK in `npm run setup` script as below.

```
    "setup": "xs-dev setup --target-branch 4.1",
```

**Comment by stc1988** [comment]
We have resolved various issues and are currently using the latest version of Moddable. Although there is an issue with the serial servo not working in the latest version, can we create a separate issue for that and close this issue?

**Comment by meganetaaan** [comment]
After a long, long battle, [we finally succeeded in getting Stack-chan’s serial servos working on the latest Moddable (v6.0.0)](https://github.com/stack-chan/stack-chan/pull/352).
